Add status code to the result of `Kitsu.prototype.request`.
wopian/kitsu pull request #1041
Opened 2024-12-01 23:24 UTC by bglimepoint

This allows looking for status codes like 206 to know it's a partial response.

2024-12-30 17:43 UTC, wopian approved these changes

2024-12-30 17:50 UTC, wopian requested changes
Thank you for this PR! Would you be able to change the variable name to statusCode for consistency and update the failing tests to have status codes expected.

2024-12-30 17:50 UTC, wopian commented on packages/kitsu/src/index.js
> +      const { data, headers: responseHeaders, status: responseStatusCode } = await this.axios.request({
```suggestion
      const { data, headers: responseHeaders, statusCode: responseStatusCode } = await this.axios.request({
```

2024-12-30 17:50 UTC, wopian commented on packages/kitsu/src/index.js
> +      return { ...deserialise(data), responseStatusCode, ...(responseHeaders ? { headers: responseHeaders } : {}) }
```suggestion
      return { 
        ...deserialise(data), 
        statusCode, 
        ...(responseHeaders ? { headers: responseHeaders } : {})
      }
```

2025-01-03 00:50 UTC, bglimepoint commented
Thanks @wopian!

Have updated the PR - including adding the status code to the other request types, but happy to adjust however you'd like :-)

2025-01-03 22:25 UTC, wopian commented
Thank you! These changes look great! After looking over it again I've opted to keep it the same as the property exposed by Axios (`status`). I've applied the changes to the PR :)

2025-01-03 22:25 UTC, wopian approved these changes

2025-01-03 22:36 UTC, merged

2025-01-03 22:42 UTC, wopian commented
The changes have been released as `kitsu@10.2.0`