Fix: Pick the meta object from actual resource rather from cached res…
wopian/kitsu pull request #783
Opened 2022-10-28 04:20 UTC by mountainfirefly

…ource if it is different

2022-10-28 08:08 UTC, wopian commented
Please can you fix the linter errors and warnings in the PR. You can run `yarn lint --fix` and it'll do most of it for you 👍

2022-10-28 08:24 UTC, wopian requested changes

2022-10-28 08:24 UTC, wopian commented on packages/kitsu-core/src/linkRelationships/index.js
> +    if (!isDeepEqual(cache.meta, resource.meta)) {
Function is missing an import

2022-10-28 08:24 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> + */
Function needs a `@private` flag at the end of the JSDoc so the non-exported function isn't rendered on the README docs

2022-10-28 08:24 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> + * @name isObject
Name is not required, it is inferred from the function name by the documentation tooling

2022-10-28 08:24 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> + * @name isDeepEqual
Name is not required as it is inferred from the function name by the documentation tooling

2022-10-28 08:24 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> + *   "firstName": "John",
ESLint will have fixed the usages of this in the test file, but it won't touch these comments.

Can you update all of these to match the projects code style. No quoted property names and single quote strings (i.e `firstName: 'John'`)

2022-10-28 08:24 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> +}, {
Missing indentation

2022-10-28 08:24 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> +  for (var key of objKeys1) {
`const key` as variable not reassigned

2022-10-28 11:05 UTC, mountainfirefly commented
Sure, will resolve these and update you soon.
Thanks

2022-10-28 12:17 UTC, wopian requested changes
Please run `yarn lint --fix` to resolve the lining errors and warnings from ESLint

2022-10-28 12:17 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> + * @private
Exported functions shouldn't have a private flag

2022-10-28 15:22 UTC, wopian requested changes

2022-10-28 15:22 UTC, wopian commented on packages/kitsu-core/src/deepEqual/index.js
> +  const objKeys2 = Object.keys(object2);
Function should check both values are objects before contining to access `Object.keys` on them. 

Tests are failing due to `undefined` and `null` values being passed in through `object1` and/or `object2`.

2022-10-30 01:26 UTC, mountainfirefly commented
@wopian Your review comments have been addressed, please check now.

Thanks

2022-10-30 17:37 UTC, wopian approved these changes

2022-10-30 17:38 UTC, merged

2022-10-30 17:39 UTC, wopian commented
Thank you. I updated the tests to include coverage of the uncovered branches and added the sample you gave in the issue as a test case in `linkedRelationships` to test the behaviour works as intended.

2022-10-30 17:55 UTC, wopian commented
Released in [10.0.3 (2022-10-30)](https://github.com/wopian/kitsu/releases/tag/v10.0.3)

2022-10-31 00:47 UTC, mountainfirefly commented
Thank you so much @wopian .